import AU_LINUX_QSDK_NHSS.QSDK.12.5_TARGET_ALL.12.5.2783.2994
Credits: https://www.right.com.cn/forum/thread-8404426-1-1.html
Note that this zip archive only contains open source codes

diff --git a/qca/configs/qsdk/setup-environment b/qca/configs/qsdk/setup-environment
--- a/qca/configs/qsdk/setup-environment
+++ b/qca/configs/qsdk/setup-environment
@@ -21,15 +21,19 @@ declare -a debug
 declare -a profile_name
 
 ret_val=1
-if [ "$#" -gt 0 ]; then
-    if [ "$1" == "-h" ]; then
-        echo "Usage: Provide target, arch and profile type for entire build (Please run \"make clean\" if this is an existing workspace)" >&2
-        exit 1
-    fi
-fi
-
+pname=""
 #echo "Help options, Run command with -h [$0 -h]"
-soc_list=("ipq807x" "ipq60xx" "ipq50xx" "ipq95xx" "ipq53xx")
+usage()
+{
+	echo "Usage: qca/configs/qsdk/setup-environment [-t <ipq807x|ipq60xx|ipq50xx|ipq95xx|ipq53xx|ipq54xx>] [-a <32|64>] [-p <256|512|16M|512enterprise|512open|bigendian|enterprise|open|premium>] [-d <y|n>] [-i <Debug|Debug+Kasan>] [-c <path to config file|n>]" 1>&2;
+	echo "For eg:"
+	echo "qca/configs/qsdk/setup-environment -t ipq807x -a 32 -p premium -d n"
+	echo "qca/configs/qsdk/setup-environment -t ipq53xx -a 64 -p open -d y -i Debug"
+	echo "qca/configs/qsdk/setup-environment -t 95xx -a 32 -p 512open -c /local/mnt/workspace/ratchaya/fig/qsdk/minent.config"
+	echo "Please run \"make clean\" if this is an existing workspace"
+	exit 1;
+}
+soc_list=("ipq807x" "ipq60xx" "ipq50xx" "ipq95xx" "ipq53xx" "ipq54xx")
 arch_list=("32" "64")
 
 populate_profile_list()
@@ -47,32 +51,107 @@ populate_profile_list()
 
 read_inputs()
 {
-	echo ""
-	echo -e "\t1) ipq807x ( Hawkeye )"
-	echo -e "\t2) ipq60xx ( Cypress )"
-	echo -e "\t3) ipq50xx ( Maple ) "
-	echo -e "\t4) ipq95xx ( Alder ) "
-	echo -e "\t5) ipq53xx ( Miami ) "
-	read -p "Please enter your choice of target[1..5] : " in_soc
-	echo ""
+	in_soc=""
+	in_arch=""
+	input=""
+	debug_in=""
+	debug_input=""
+	config_file=""
+	local OPTIND
+	while getopts ":t:a:p:d:i:c:h" arg;do
+		case "${arg}" in
+			t)
+				in_soc=${OPTARG}
+				if [[ "${in_soc}" != "ipq807x" && "${in_soc}" != "ipq60xx" && "${in_soc}" != "ipq50xx" && "${in_soc}" != "ipq95xx" && "${in_soc}" != "ipq53xx" && "${in_soc}" != "ipq54xx" ]]; then
+					echo -e "\n\033[0;31mInvalid target passed as input - ${in_soc}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			a)
+				in_arch=${OPTARG}
+				if [[ "${in_arch}" != "32" && "${in_arch}" != "64" ]]; then
+					echo -e "\n\033[0;31mInvalid build type passed as input - ${in_arch}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			p)
+				input=${OPTARG}
+				if [[ "${input}" != "256" && "${input}" != "512" && "${input}" != "16M" && "${input}" != "512enterprise" && "${input}" != "512open" && "${input}" != "bigendian" && "${input}" != "enterprise" && "${input}" != "enterprise" && "${input}" != "open" && "${input}" != "premium" ]]; then
+				echo -e "\n\033[0;31mInvalid profile passed as input - ${input}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			d)
+				debug_in=${OPTARG}
+				if [[ "${debug_in}" != "y" && "${debug_in}" != "n" ]]; then
+					echo -e "\n\033[0;31mInvalid debug option passed as input - ${debug_in}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			i)
+				debug_input=${OPTARG}
+				if [[ "${debug_input}" != "Debug" && "${debug_input}" != "Debug+Kasan" ]]; then
+					echo -e "\n\033[0;31mInvalid debug profile passed as input - ${debug_input}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			c)
+				config_file=${OPTARG}
+				if [[ $config_file == "n" ]]; then
+					:
+				elif [[ ! -f "${config_file}" ]]; then
+					echo -e "\n\033[0;31mInvalid config file passed as input - ${config_file}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
 
-	if [[ $in_soc -lt 1 || $in_soc -gt 5 ]]; then
-	        echo "Wrong input.. exiting"
-		return 0
+			h | *)
+				usage
+				exit 0
+				;;
+		esac
+	done
+	shift "$((OPTIND-1))"
+
+	if [ -z $in_soc ]; then
+		echo ""
+		echo -e "\t1) ipq807x ( Hawkeye )"
+		echo -e "\t2) ipq60xx ( Cypress )"
+		echo -e "\t3) ipq50xx ( Maple ) "
+		echo -e "\t4) ipq95xx ( Alder ) "
+		echo -e "\t5) ipq53xx ( Miami ) "
+		echo -e "\t6) ipq54xx ( Marina )"
+		read -p "Please enter your choice of target[1..6] : " in_soc
+		echo ""
+
+		if [[ $in_soc -lt 1 || $in_soc -gt 6 ]]; then
+			echo "Wrong input.. exiting"
+			return 1
+		fi
+		in_soc=${soc_list[$in_soc-1]}
 	fi
 
-	echo -e "\t1) 32 Bit"
-	echo -e "\t2) 64 bit"
-	read -p "Please enter your choice of build type[1..2] : " in_arch
-	echo ""
+	if [ -z $in_arch ]; then
+		echo -e "\t1) 32 Bit"
+		echo -e "\t2) 64 bit"
+		read -p "Please enter your choice of build type[1..2] : " in_arch
+		echo ""
 
-	if [[ $in_arch -lt 1 || $in_arch -gt 2 ]]; then
-	        echo "Wrong input.. exiting"
-		return 0
+		if [[ $in_arch -lt 1 || $in_arch -gt 2 ]]; then
+		        echo "Wrong input.. exiting"
+			return 1
+		fi
+		in_arch=${arch_list[$in_arch-1]}
 	fi
 
-	qsdk_target=${soc_list[$in_soc-1]}
-	arch=${arch_list[$in_arch-1]}
+	qsdk_target=$in_soc
+	arch=$in_arch
 	if [ "$arch" -eq "64" ];then
 		qsdk_subtarget="generic"
 	else if [ "$arch" -eq "32" ];then
@@ -80,33 +159,103 @@ read_inputs()
 		fi
 	fi
 
-	echo -e "\n\033[36m**** List of supported QSDK profiles *****\033[0m"
 	populate_profile_list
-	index=1
-	for i in ${profile[@]};do
-		echo -e "\t$index) ${i:4}"
-		index=$(( $index+1 ))
-	done
-	read -p "Choose the profile [1..${#profile[@]}] : " input
-	if [[ $input -lt 1 || $input -gt ${#profile[@]} ]];then
-		echo "Please enter a valid input...Exiting"
+	if [ -z $input ]; then
+		echo -e "\n\033[36m**** List of supported QSDK profiles *****\033[0m"
+		index=1
+		echo "	0) Default"
+		for i in ${profile[@]};do
+			echo -e "\t$index) ${i:4}"
+			index=$(( $index+1 ))
+		done
+		read -p "Choose the profile [1..${#profile[@]}] : " input
+		if [[ $input -lt 0 || $input -gt ${#profile[@]} ]];then
+			echo "Please enter a valid input...Exiting"
+			return 1
+		fi
+	else
+		index=0
+		string="ipq_"$input
+		for i in ${profile[@]};do
+			index=$(( $index+1 ))
+			if [ ${string} == ${i} ]; then
+				break
+			fi
+		done
+		input="$index"
+	fi
+
+	if [[ $input -eq 0 ]];then
+		pname="QSDK_Default"
+		echo "CONFIG_TARGET_${qsdk_target}=y" > $TOP_DIR/.config
+		echo "CONFIG_TARGET_${qsdk_target}_${qsdk_subtarget}=y" >> $TOP_DIR/.config
+		echo CONFIG_TARGET_MULTI_PROFILE=y >> $TOP_DIR/.config
+		echo CONFIG_TARGET_ALL_PROFILES=y >> $TOP_DIR/.config
+		echo "# CONFIG_KERNEL_WERROR is not set" >> $TOP_DIR/.config
 		return 0
 	fi
 	declare qsdk_profile=${profile[$(( $input -1 ))]}
 	pfile=${profile[$(( $input -1 ))]}
 	pname=${profile_name[$(( $input -1 ))]}
-	echo -e "\n\033[36mSelected configuration: ${qsdk_target} - ${qsdk_subtarget} - ${qsdk_profile}\033[0m"
-	read -p "Debug build required ? [y/n] : " debug_in
-	case $debug_in in
-		'y') debug=("Debug" "Debug+Kasan")
-			# Check for debug builds
-			index=1
-			for i in ${debug[@]};do
-				echo -e "\t$index) $i"
-				index=$(( $index+1 ))
-			done
 
-			read -p "Choose the option for debug build : " debug_input
+	if [ "$arch" -eq "64" ];then
+		if [[ $qsdk_profile == *"512"* || $qsdk_profile == *"256"* || $qsdk_profile == *"16"* ]];then
+			echo -e "\033[0;31m$qsdk_profile is not supported for 64 build type..\033[0m"
+			return 1
+		fi
+	fi
+	echo -e "\n\033[36mSelected configuration: ${qsdk_target} - ${qsdk_subtarget} - ${qsdk_profile}\033[0m"
+
+	if [ -z $config_file ]; then
+		read -p "Do you want to pass config file ? [y/n] : " config_in
+		if [[ $config_in == "y" ]]; then
+			read -p "Enter the path to config file : " config_file
+			if [[ ! -f "${config_file}" ]]; then
+					echo "Please enter a valid config file path...Exiting"
+					return 1
+			fi
+		fi
+	fi
+	# running sed command to set ARCH for Big Endian profile
+	if [ ${qsdk_profile} == "ipq_bigendian" ]
+	then
+		if [ $arch == 64 ]
+		then
+			sed 's/ARCH:=aarch64/ARCH:=aarch64_be/g' -i $TOP_DIR/target/linux/feeds/${qsdk_target}/Makefile
+		else
+			sed 's/ARCH:=arm/ARCH:=armeb/g' -i $TOP_DIR/target/linux/feeds/${qsdk_target}/${qsdk_target}_32/target.mk
+		fi
+	else
+		sed 's/ARCH:=aarch64_be/ARCH:=aarch64/g' -i $TOP_DIR/target/linux/feeds/${qsdk_target}/Makefile
+		sed 's/ARCH:=armeb/ARCH:=arm/g' -i $TOP_DIR/target/linux/feeds/${qsdk_target}/${qsdk_target}_32/target.mk
+	fi
+
+	if [ -z $debug_in ]; then
+		read -p "Debug build required ? [y/n] : " debug_in
+	fi
+
+	case $debug_in in
+		'y')    debug=("Debug" "Debug+Kasan")
+			if [ -z $debug_input ]; then
+				debug=("Debug" "Debug+Kasan")
+				# Check for debug builds
+				index=1
+				for i in ${debug[@]};do
+					echo -e "\t$index) $i"
+					index=$(( $index+1 ))
+				done
+
+				read -p "Choose the option for debug build : " debug_input
+			else
+				index=1
+				for i in ${debug[@]};do
+					if [ ${debug_input} == ${i} ]; then
+						break
+					fi
+					index=$(( $index+1 ))
+				done
+				debug_input=$index
+			fi
 			case $debug_input in
 				1)	if [[ "$pname" = QSDK_16M ]];then
 					       cat $SCRIPT_DIR/${pfile}.config \
@@ -122,7 +271,7 @@ read_inputs()
 				       ;;
 
 				*)	echo "Wrong input .... exiting"
-					return 0
+					return 1
 					;;
 		       esac
 		       ;;
@@ -132,7 +281,7 @@ read_inputs()
 		       ;;
 		*)
 			echo "Wrong input .... exiting"
-			return 0
+			return 1
 			;;
 	esac
 	echo "CONFIG_TARGET_${qsdk_target}=y" >> $TOP_DIR/.config
@@ -140,18 +289,34 @@ read_inputs()
 	# Set subtarget
 	echo "CONFIG_TARGET_${qsdk_target}_${qsdk_subtarget}=y" >> $TOP_DIR/.config
 	echo "CONFIG_TARGET_${qsdk_target}_${qsdk_subtarget}_${pname}=y" >> $TOP_DIR/.config
-	return 1
+	echo "# CONFIG_KERNEL_WERROR is not set" >> $TOP_DIR/.config
+	return 0
 }
 
-read_inputs
+read_inputs $@
 ret_val=$?
-if [ $ret_val != 0 ];then
+if [ $ret_val == 0 ];then
 	cd $TOP_DIR
 	umask 022
+	date +%s > version.date
 	make package/symlinks
 	echo -e "\n================= Executing "make defconfig" =============="
 	make defconfig
+	if [[ -e $config_file ]]; then
+		cat $config_file >> $TOP_DIR/.config
+	fi
 
+	echo -e "\033[0;32m# Selected target:      $(grep CONFIG_TARGET_BOARD= .config | cut -d "\"" -f 2)\033[0m"
+	echo -e "\033[0;32m# Selected subtarget:   $(grep CONFIG_TARGET_SUBTARGET= .config | cut -d "\"" -f 2)\033[0m"
+	if grep -q -oP "CONFIG_KERNEL_KASAN=y" .config; then
+		config_ext="_Kasan";
+	elif grep -q -oP "CONFIG_DEBUG=y" .config; then
+		config_ext="_Debug";
+	else
+		config_ext="";
+	fi
+	echo -e "\033[0;32m# Selected profile:     "${pname}"$config_ext\033[0m"
+	echo "#"
 	echo ""
 	echo '================= .config is generated, you can build using below commands =============='
 	echo ""
diff --git a/qca/feeds/packages/net/adblock/files/adblock.init b/qca/feeds/packages/net/adblock/files/adblock.init
--- a/qca/feeds/packages/net/adblock/files/adblock.init
+++ b/qca/feeds/packages/net/adblock/files/adblock.init
@@ -1,56 +1,40 @@
 #!/bin/sh /etc/rc.common
-# Copyright (c) 2015-2020 Dirk Brenken (dev@brenken.org)
+# Copyright (c) 2015-2022 Dirk Brenken (dev@brenken.org)
 # This is free software, licensed under the GNU General Public License v3.
 
-# set (s)hellcheck exceptions
-# shellcheck disable=1091,2010,2016,2034,2039,2059,2086,2091,2129,2143,2154,2181,2183,2188
+# disable (s)hellcheck in release
+# shellcheck disable=all
 
 START=30
 USE_PROCD=1
 
-EXTRA_COMMANDS="suspend resume query report list timer status version"
-EXTRA_HELP="	status	Service status
-	suspend	Suspend adblock processing
-	resume	Resume adblock processing
-	query	<domain> Query active blocklists and backups for a specific domain
-	report	[<search>] Print DNS statistics with an optional search parameter
-	list	[[<add>|<remove>] [source(s)]] List available adblock sources or add/remove them from config
-	timer	<action> <hour> [<minute>] [<weekday>] Set a cron based update interval
-	version	print version information"
+extra_command "suspend" "Suspend adblock processing"
+extra_command "resume" "Resume adblock processing"
+extra_command "query" "<domain> Query active blocklists and backups for a specific domain"
+extra_command "report" "[[<cli>|<mail>|<gen>|<json>] [<top_count>] [<res_count>] [<search>]] Print DNS statistics with an optional search parameter"
+extra_command "list" "[<add>|<add_utc>|<add_eng>|<add_stb>|<remove>|<remove_utc>|<remove_eng>|<remove_stb>] <source(s)> List/Edit available sources"
+extra_command "timer" "[<add> <tasks> <hour> [<minute>] [<weekday>]]|[<remove> <line no.>] List/Edit cron update intervals"
 
 adb_init="/etc/init.d/adblock"
 adb_script="/usr/bin/adblock.sh"
 adb_pidfile="/var/run/adblock.pid"
 
-if [ -s "${adb_pidfile}" ] && { [ "${action}" = "start" ] || [ "${action}" = "stop" ] || \
-	[ "${action}" = "restart" ] || [ "${action}" = "reload" ] || [ "${action}" = "report" ] || \
-	[ "${action}" = "suspend" ] || [ "${action}" = "resume" ] || [ "${action}" = "query" ] || \
-	{ [ "${action}" = "list" ] && [ -n "${1}" ]; }; }
-then
-	exit 0
+if [ -s "${adb_pidfile}" ] && { [ "${action}" = "start" ] || [ "${action}" = "stop" ] ||
+	[ "${action}" = "restart" ] || [ "${action}" = "reload" ] || [ "${action}" = "report" ] ||
+	[ "${action}" = "suspend" ] || [ "${action}" = "resume" ] || [ "${action}" = "query" ] ||
+	{ [ "${action}" = "list" ] && [ -n "${1}" ]; }; }; then
+	return 0
 fi
 
-version()
-{
-	rc_procd "${adb_script}" version
-}
-
-boot()
-{
-	[ -s "${adb_pidfile}" ] && > "${adb_pidfile}"
+boot() {
+	[ -s "${adb_pidfile}" ] && : >"${adb_pidfile}"
 	rc_procd start_service
 }
 
-start_service()
-{
-	if [ "$("${adb_init}" enabled; printf "%u" ${?})" -eq 0 ]
-	then
-		if [ "${action}" = "boot" ]
-		then
-			if [ -n "$(uci_get adblock global adb_trigger)" ]
-			then
-				return 0
-			fi
+start_service() {
+	if "${adb_init}" enabled; then
+		if [ "${action}" = "boot" ]; then
+			[ -n "$(uci_get adblock global adb_trigger)" ] && return 0
 		fi
 		procd_open_instance "adblock"
 		procd_set_param command "${adb_script}" "${@}"
@@ -62,206 +46,224 @@ start_service()
 	fi
 }
 
-reload_service()
-{
+reload_service() {
 	rc_procd start_service reload
 }
 
-stop_service()
-{
+stop_service() {
 	rc_procd "${adb_script}" stop
 }
 
-restart()
-{
+restart() {
 	rc_procd start_service restart
 }
 
-suspend()
-{
+suspend() {
 	rc_procd start_service suspend
 }
 
-resume()
-{
+resume() {
 	rc_procd start_service resume
 }
 
-query()
-{
+query() {
 	rc_procd "${adb_script}" query "${1}"
 }
 
-report()
-{
-	rc_procd "${adb_script}" report "${1:-"+"}" "${2:-"50"}" "${3:-"true"}" "${4:-"cli"}"
+report() {
+	rc_procd "${adb_script}" report "${1:-"cli"}" "${2}" "${3}" "${4}"
 }
 
-list()
-{
-	local src_archive src_file src_enabled enabled name action="${1}"
+list() {
+	local src_archive src_file src_enabled enabled name utc_list size focus descurl action="${1}"
 
-	if [ "${action}" = "add" ] || [ "${action}" = "remove" ]
-	then
+	if [ "${action%_*}" = "add" ] || [ "${action%_*}" = "remove" ]; then
 		shift
-		for name in "${@}"
-		do
-			if [ "${action}" = "add" ]
-			then
-				if [ -z "$(uci_get adblock global adb_sources | grep -Fo "${name}")" ]
-				then
-					uci_add_list adblock global adb_sources "${name}"
-					printf "%s\\n" "::: adblock source '${name}' added to config"
-				fi
-			else
-				if [ -n "$(uci_get adblock global adb_sources | grep -Fo "${name}")" ]
-				then
-					uci_remove_list adblock global adb_sources "${name}"
-					printf "%s\\n" "::: adblock source '${name}' removed from config"
-				fi
-			fi
+		for name in "${@}"; do
+			case "${action}" in
+				"add")
+					if ! uci_get adblock global adb_sources | grep -q "${name}"; then
+						uci_add_list adblock global adb_sources "${name}"
+						printf "%s\n" "::: adblock source '${name}' added to config"
+					fi
+					;;
+				"remove")
+					if uci_get adblock global adb_sources | grep -q "${name}"; then
+						uci_remove_list adblock global adb_sources "${name}"
+						printf "%s\n" "::: adblock source '${name}' removed from config"
+					fi
+					;;
+				"add_utc")
+					if ! uci_get adblock global adb_utc_sources | grep -q "${name}"; then
+						uci_add_list adblock global adb_utc_sources "${name}"
+						printf "%s\n" "::: adblock utcapitole '${name}' added to config"
+					fi
+					;;
+				"remove_utc")
+					if uci_get adblock global adb_utc_sources | grep -q "${name}"; then
+						uci_remove_list adblock global adb_utc_sources "${name}"
+						printf "%s\n" "::: adblock utcapitole '${name}' removed from config"
+					fi
+					;;
+				"add_eng")
+					if ! uci_get adblock global adb_eng_sources | grep -q "${name}"; then
+						uci_add_list adblock global adb_eng_sources "${name}"
+						printf "%s\n" "::: adblock energized '${name}' added to config"
+					fi
+					;;
+				"remove_eng")
+					if uci_get adblock global adb_eng_sources | grep -q "${name}"; then
+						uci_remove_list adblock global adb_eng_sources "${name}"
+						printf "%s\n" "::: adblock energized '${name}' removed from config"
+					fi
+					;;
+				"add_stb")
+					if ! uci_get adblock global adb_stb_sources | grep -q "${name}"; then
+						uci_add_list adblock global adb_stb_sources "${name}"
+						printf "%s\n" "::: adblock stevenblack '${name}' added to config"
+					fi
+					;;
+				"remove_stb")
+					if uci_get adblock global adb_stb_sources | grep -q "${name}"; then
+						uci_remove_list adblock global adb_stb_sources "${name}"
+						printf "%s\n" "::: adblock stevenblack '${name}' removed from config"
+					fi
+					;;
+			esac
 		done
-		if [ -n "$(uci -q changes adblock)" ]
-		then
-			uci_commit adblock
-			"${adb_init}" start
-		fi
+		[ -n "$(uci -q changes adblock)" ] && { uci_commit adblock; "${adb_init}" start; }
 	else
 		src_archive="$(uci_get adblock global adb_srcarc "/etc/adblock/adblock.sources.gz")"
 		src_file="$(uci_get adblock global adb_srcfile "/tmp/adb_sources.json")"
 		src_enabled="$(uci -q show adblock.global.adb_sources)"
-		if [ -r "${src_archive}" ]
-		then
-			zcat "${src_archive}" > "${src_file}"
-		else
-			printf "%s\\n" "::: adblock source archive '${src_archive}' not found"
-		fi
-		if [ -r "${src_file}" ]
-		then
+		[ -r "${src_archive}" ] && zcat "${src_archive}" >"${src_file}" || printf "%s\n" "::: adblock source archive '${src_archive}' not found"
+
+		if [ -r "${src_file}" ]; then
 			src_enabled="${src_enabled#*=}"
 			src_enabled="${src_enabled//\'}"
-			printf "%s\\n" "::: Available adblock sources"
-			printf "%s\\n" ":::"
-			printf "%-25s%-10s%-7s%-21s%s\\n" "    Name" "Enabled" "Size" "Focus" "Info URL"
-			printf "%s\\n" "    -------------------------------------------------------------------"
+			printf "%s\n" "::: Available adblock sources"
+			printf "%s\n" ":::"
+			printf "%-25s%-10s%-7s%-21s%s\n" "    Name" "Enabled" "Size" "Focus" "Info URL"
+			printf "%s\n" "    -------------------------------------------------------------------"
 			json_load_file "${src_file}"
 			json_get_keys keylist
-			for key in ${keylist}
-			do
+			for key in ${keylist}; do
 				json_select "${key}"
 				json_get_var size "size"
 				json_get_var focus "focus"
 				json_get_var descurl "descurl"
 				json_get_var url "url"
 				json_get_var rule "rule"
-				if [ -n "${url}" ] && [ -n "${rule}" ]
-				then
-					if [ -n "$(printf "%s" "${src_enabled}" | grep -Fo "${key}")" ]
-					then
+				if [ -n "${url}" ] && [ -n "${rule}" ]; then
+					if printf "%s" "${src_enabled}" | grep -q "${key}"; then
 						enabled="x"
 					else
 						enabled=" "
 					fi
 					src_enabled="${src_enabled/${key}}"
-					printf "  + %-21s%-10s%-7s%-21s%s\\n" "${key:0:20}" "${enabled}" "${size:0:3}" "${focus:0:20}" "${descurl:0:50}"
+					printf "  + %-21s%-10s%-7s%-21s%s\n" "${key:0:20}" "${enabled}" "${size:0:3}" "${focus:0:20}" "${descurl:0:50}"
 				else
 					src_enabled="${src_enabled} ${key}"
 				fi
 				json_select ..
 			done
-			if [ -n "${src_enabled// }" ]
-			then
-				printf "%s\\n" "    ----------------------------------------------"
-				printf "%s\\n" "    Sources without valid configuration"
-				printf "%s\\n" "    ----------------------------------------------"
-				for key in ${src_enabled}
-				do
-					printf "  - %s\\n" "${key:0:20}"
+			utc_list="$(uci_get adblock global adb_utc_sources "-")"
+			eng_list="$(uci_get adblock global adb_eng_sources "-")"
+			stb_list="$(uci_get adblock global adb_stb_sources "-")"
+			printf "%s\n" "    ---------------------------------------------------------------------------"
+			printf "  * %s\n" "Configured utcapitole categories: ${utc_list// /, }"
+			printf "  * %s\n" "Configured energized variants: ${eng_list// /, }"
+			printf "  * %s\n" "Configured stevenblack variants: ${stb_list// /, }"
+
+			if [ -n "${src_enabled// }" ]; then
+				printf "%s\n" "    ---------------------------------------------------------------------------"
+				printf "%s\n" "    Sources with invalid configuration"
+				printf "%s\n" "    ---------------------------------------------------------------------------"
+				for key in ${src_enabled}; do
+					printf "  - %s\n" "${key:0:20}"
 				done
 			fi
 		else
-			printf "%s\\n" "::: adblock source file '${src_file}' not found"
+			printf "%s\n" "::: adblock source file '${src_file}' not found"
 		fi
 	fi
 }
 
-status()
-{
+status() {
 	status_service
 }
 
-status_service()
-{
-	local key keylist value rtfile
+status_service() {
+	local key keylist value idxval values type rtfile
 
 	rtfile="$(uci_get adblock global adb_rtfile "/tmp/adb_runtime.json")"
-	if [ -s "${rtfile}" ]
-	then
-		printf "%s\\n" "::: adblock runtime information"
-		json_load_file "${rtfile}"
-		json_select data
-		json_get_keys keylist
-		for key in ${keylist}
-		do
-			json_get_var value "${key}"
-			if [ "${key}" = "active_sources" ]
-			then
+
+	json_load_file "${rtfile}" >/dev/null 2>&1
+	json_get_keys keylist
+	if [ -n "${keylist}" ]; then
+		printf "%s\n" "::: adblock runtime information"
+		for key in ${keylist}; do
+			json_get_var value "${key}" >/dev/null 2>&1
+			if [ "${key%_*}" = "active" ]; then
 				printf "  + %-15s : " "${key}"
-				json_select "${key}"
-				index=1
-				while json_get_type status "${index}" && [ "${status}" = "object" ]
-				do
-					json_get_values source "${index}"
-					printf "%s " "${source}"
-					index=$((index+1))
+				json_select "${key}" >/dev/null 2>&1
+				values=""
+				index="1"
+				while json_get_type type "${index}" && [ "${type}" = "object" ]; do
+					json_get_values idxval "${index}" >/dev/null 2>&1
+					if [ "${index}" = "1" ]; then
+						values="${idxval}"
+					else
+						values="${values}, ${idxval}"
+					fi
+					index="$((index + 1))"
 				done
-				printf "\\n"
+				values="$(printf "%s" "${values}" | awk '{NR=1;max=98;if(length($0)>max+1)while($0){if(NR==1){print substr($0,1,max)}else{printf"%-22s%s\n","",substr($0,1,max)}{$0=substr($0,max+1);NR=NR+1}}else print}')"
+				printf "%s\n" "${values:-"-"}"
 				json_select ".."
 			else
-				printf "  + %-15s : %s\\n" "${key}" "${value}"
+				printf "  + %-15s : %s\n" "${key}" "${value:-"-"}"
 			fi
 		done
 	else
-		printf "%s\\n" "::: no adblock runtime information available"
+		printf "%s\n" "::: no adblock runtime information available"
 	fi
 }
 
-timer()
-{
-	local action="${1}" hour="${2}" minute="${3:-0}" weekday="${4:-"*"}"
+timer() {
+	local cron_file cron_content cron_lineno action="${1:-"list"}" cron_tasks="${2}" hour="${3}" minute="${4:-0}" weekday="${5:-"*"}"
 
-	hour="${hour//[[:alpha:]]/}"
-	minute="${minute//[[:alpha:]]/}"
-	if [ -n "${action}" ] && [ -n "${hour}" ] && [ -n "${minute}" ] && [ -n "${weekday}" ] && \
-		[ "${hour}" -ge 0 ] && [ "${hour}" -le 23 ] && \
-		[ "${minute}" -ge 0 ] && [ "${minute}" -le 59 ]
-	then
-		if [ -r "/etc/crontabs/root" ]
-		then
-			search="${adb_init//\//\\/}"
-			search="${search//./\\.}"
-			sed -i "/${search}/d" "/etc/crontabs/root"
+	cron_file="/etc/crontabs/root"
+
+	if [ -s "${cron_file}" ] && [ "${action}" = "list" ]; then
+		awk '{print NR ">  " $0}' "${cron_file}"
+	elif [ -x "/etc/init.d/cron" ] && [ "${action}" = "add" ]; then
+		hour="${hour//[[:alpha:]]/}"
+		minute="${minute//[[:alpha:]]/}"
+		if [ -n "${cron_tasks}" ] && [ -n "${hour}" ] && [ -n "${minute}" ] && [ -n "${weekday}" ] &&
+			[ "${hour}" -ge 0 ] && [ "${hour}" -le 23 ] &&
+			[ "${minute}" -ge 0 ] && [ "${minute}" -le 59 ]; then
+			printf "%02d %02d %s\n" "${minute}" "${hour}" "* * ${weekday} ${adb_init} ${cron_tasks}" >>"${cron_file}"
+			/etc/init.d/cron restart
 		fi
-		printf "%02d %02d %s\\n" "${minute}" "${hour}" "* * ${weekday} ${adb_init} ${action}" >> "/etc/crontabs/root"
-		/etc/init.d/cron restart
-	else
-		printf "%s\\n" "::: the refresh timer could not been updated"
+	elif [ -x "/etc/init.d/cron" ] && [ -s "${cron_file}" ] && [ "${action}" = "remove" ]; then
+		cron_tasks="${cron_tasks//[[:alpha:]]/}"
+		cron_lineno="$(awk 'END{print NR}' "${cron_file}")"
+		cron_content="$(awk '{print $0}' "${cron_file}")"
+		if [ "${cron_tasks:-"0"}" -le "${cron_lineno:-"1"}" ] && [ -n "${cron_content}" ]; then
+			printf "%s\n" "${cron_content}" | awk "NR!~/^${cron_tasks}$/" >"${cron_file}"
+			/etc/init.d/cron restart
+		fi
 	fi
 }
 
-service_triggers()
-{
-	local trigger delay type
+service_triggers() {
+	local iface delay
 
-	trigger="$(uci_get adblock global adb_trigger)"
-	delay="$(uci_get adblock global adb_triggerdelay "2")"
-	type="$(uci_get adblock global adb_starttype "start")"
+	iface="$(uci_get adblock global adb_trigger)"
+	delay="$(uci_get adblock global adb_triggerdelay "5")"
+	PROCD_RELOAD_DELAY="$((delay * 1000))"
 
-	PROCD_RELOAD_DELAY=$((delay*1000))
-
-	if [ -n "${trigger}" ]
-	then
-		procd_add_interface_trigger "interface.*.up" "${trigger}" "${adb_init}" "${type}"
-	fi
+	[ -n "${iface}" ] && procd_add_interface_trigger "interface.*.up" "${iface}" "${adb_init}" "start"
 	procd_add_reload_trigger "adblock"
 }
diff --git a/target/imagebuilder/files/Makefile b/target/imagebuilder/files/Makefile
--- a/target/imagebuilder/files/Makefile
+++ b/target/imagebuilder/files/Makefile
@@ -13,6 +13,7 @@ export TOPDIR LC_ALL LANG
 export OPENWRT_VERBOSE=s
 all: help
 
+export ORIG_PATH:=$(if $(ORIG_PATH),$(ORIG_PATH),$(PATH))
 export PATH:=$(TOPDIR)/staging_dir/host/bin:$(PATH)
 
 ifneq ($(OPENWRT_BUILD),1)
@@ -27,6 +28,7 @@ include $(INCLUDE_DIR)/rootfs.mk
 
 include $(INCLUDE_DIR)/version.mk
 export REVISION
+export SOURCE_DATE_EPOCH
 
 define Helptext
 Available Commands:
@@ -34,8 +36,11 @@ Available Commands:
 	info:	Show a list of available target profiles
 	clean:	Remove images and temporary build files
 	image:	Build an image (see below for more information).
+	manifest: Show all package that will be installed into the image
+	package_whatdepends: Show which packages have a dependency on this
+	package_depends: Show installation dependency of the package
 
-Building images:
+image:
 	By default 'make image' will create an image with the default
 	target profile and package set. You can use the following parameters
 	to change that:
@@ -46,13 +51,29 @@ Building images:
 	make image BIN_DIR="<path>" # alternative output directory for the images
 	make image EXTRA_IMAGE_NAME="<string>" # Add this to the output image filename (sanitized)
 	make image DISABLED_SERVICES="<svc1> [<svc2> [<svc3> ..]]" # Which services in /etc/init.d/ should be disabled
+	make image ADD_LOCAL_KEY=1 # store locally generated signing key in built images
+	make image ROOTFS_PARTSIZE="<size>" # override the default rootfs partition size in MegaBytes
 
-Print manifest:
+manifest:
 	List "all" packages which get installed into the image.
 	You can use the following parameters:
 
 	make manifest PROFILE="<profilename>" # override the default target profile
 	make manifest PACKAGES="<pkg1> [<pkg2> [<pkg3> ...]]" # include extra packages
+	make manifest STRIP_ABI=1 # remove ABI version from printed package names
+
+
+package_whatdepends:
+	List "all" packages that have a dependency on this package
+	You can use the following parameters:
+
+	make package_whatdepends PACKAGE="<pkg>"
+
+package_depends:
+	List "all" packages dependency of the package
+	You can use the following parameters:
+
+	make package_depends PACKAGE="<pkg>"
 
 endef
 $(eval $(call shexport,Helptext))
@@ -64,8 +85,10 @@ help: FORCE
 # override variables from rules.mk
 PACKAGE_DIR:=$(TOPDIR)/packages
 LISTS_DIR:=$(subst $(space),/,$(patsubst %,..,$(subst /,$(space),$(TARGET_DIR))))$(DL_DIR)
+export OPKG_KEYS:=$(TOPDIR)/keys
 OPKG:=$(call opkg,$(TARGET_DIR)) \
 	-f $(TOPDIR)/repositories.conf \
+	--verify-program $(SCRIPT_DIR)/opkg-key \
 	--cache $(DL_DIR) \
 	--lists-dir $(LISTS_DIR)
 
@@ -98,13 +121,16 @@ staging_dir/host/.prereq-build: include/prereq-build.mk
 
 _call_info: FORCE
 	echo 'Current Target: "$(TARGETID)"'
+	echo 'Current Architecture: "$(ARCH)"'
 	echo 'Current Revision: "$(REVISION)"'
 	echo 'Default Packages: $(DEFAULT_PACKAGES)'
 	echo 'Available Profiles:'
 	echo; $(PROFILE_LIST)
 
-BUILD_PACKAGES:=$(USER_PACKAGES) $(sort $(DEFAULT_PACKAGES) $($(USER_PROFILE)_PACKAGES) kernel)
+BUILD_PACKAGES:=$(sort $(DEFAULT_PACKAGES) $($(USER_PROFILE)_PACKAGES) kernel)
 # "-pkgname" in the package list means remove "pkgname" from the package list
+BUILD_PACKAGES:=$(filter-out $(filter -%,$(BUILD_PACKAGES)) $(patsubst -%,%,$(filter -%,$(BUILD_PACKAGES))),$(BUILD_PACKAGES))
+BUILD_PACKAGES:=$(USER_PACKAGES) $(BUILD_PACKAGES)
 BUILD_PACKAGES:=$(filter-out $(filter -%,$(BUILD_PACKAGES)) $(patsubst -%,%,$(filter -%,$(BUILD_PACKAGES))),$(BUILD_PACKAGES))
 PACKAGES:=
 
@@ -126,19 +152,24 @@ _call_manifest: FORCE
 	mkdir -p $(TARGET_DIR) $(BIN_DIR) $(TMP_DIR) $(DL_DIR)
 	$(MAKE) package_reload >/dev/null
 	$(MAKE) package_install >/dev/null
-	$(OPKG) list-installed
+	$(OPKG) list-installed $(if $(STRIP_ABI),--strip-abi)
 
 package_index: FORCE
 	@echo >&2
 	@echo Building package index... >&2
 	@mkdir -p $(TMP_DIR) $(TARGET_DIR)/tmp
 	(cd $(PACKAGE_DIR); $(SCRIPT_DIR)/ipkg-make-index.sh . > Packages && \
-		gzip -9nc Packages > Packages.gz \
+		gzip -9nc Packages > Packages.gz; \
+		$(if $(CONFIG_SIGNATURE_CHECK), \
+			$(STAGING_DIR_HOST)/bin/usign -S -m Packages -s $(BUILD_KEY)) \
 	) >/dev/null 2>/dev/null
 	$(OPKG) update >&2 || true
 
 package_reload:
-	if [ ! -f "$(PACKAGE_DIR)/Packages" ] || [ ! -f "$(PACKAGE_DIR)/Packages.gz" ] || [ "`find $(PACKAGE_DIR) -cnewer $(PACKAGE_DIR)/Packages.gz`" ]; then \
+	if [ -d "$(PACKAGE_DIR)" ] && ( \
+			[ ! -f "$(PACKAGE_DIR)/Packages" ] || \
+			[ ! -f "$(PACKAGE_DIR)/Packages.gz" ] || \
+			[ "`find $(PACKAGE_DIR) -cnewer $(PACKAGE_DIR)/Packages.gz`" ] ); then \
 		echo "Package list missing or not up-to-date, generating it." >&2 ;\
 		$(MAKE) package_index; \
 	else \
@@ -153,8 +184,8 @@ package_list: FORCE
 package_install: FORCE
 	@echo
 	@echo Installing packages...
-	$(OPKG) install $(firstword $(wildcard $(PACKAGE_DIR)/libc_*.ipk $(PACKAGE_DIR)/base/libc_*.ipk))
-	$(OPKG) install $(firstword $(wildcard $(PACKAGE_DIR)/kernel_*.ipk $(PACKAGE_DIR)/base/kernel_*.ipk))
+	$(OPKG) install $(firstword $(wildcard $(LINUX_DIR)/libc_*.ipk $(PACKAGE_DIR)/libc_*.ipk))
+	$(OPKG) install $(firstword $(wildcard $(LINUX_DIR)/kernel_*.ipk $(PACKAGE_DIR)/kernel_*.ipk))
 	$(OPKG) install $(BUILD_PACKAGES)
 
 prepare_rootfs: FORCE
@@ -162,14 +193,19 @@ prepare_rootfs: FORCE
 	@echo Finalizing root filesystem...
 
 	$(CP) $(TARGET_DIR) $(TARGET_DIR_ORIG)
+	$(if $(CONFIG_SIGNATURE_CHECK), \
+		$(if $(ADD_LOCAL_KEY), \
+			OPKG_KEYS=$(TARGET_DIR)/etc/opkg/keys/ \
+			$(SCRIPT_DIR)/opkg-key add $(BUILD_KEY).pub \
+		) \
+	)
 	$(call prepare_rootfs,$(TARGET_DIR),$(USER_FILES),$(DISABLED_SERVICES))
-
 
 build_image: FORCE
 	@echo
 	@echo Building images...
 	rm -rf $(BUILD_DIR)/json_info_files/
-	$(NO_TRACE_MAKE) -C target/linux/$(BOARD)/image install TARGET_BUILD=1 IB=1 EXTRA_IMAGE_NAME="$(EXTRA_IMAGE_NAME)" \
+	$(NO_TRACE_MAKE) -C $(PLATFORM_DIR)/image install TARGET_BUILD=1 IB=1 EXTRA_IMAGE_NAME="$(EXTRA_IMAGE_NAME)" \
 		$(if $(USER_PROFILE),PROFILE="$(USER_PROFILE)")
 
 $(BIN_DIR)/profiles.json: FORCE
@@ -203,22 +239,59 @@ ifneq ($(PROFILE),)
   endif
 endif
 
+_check_keys: FORCE
+ifneq ($(CONFIG_SIGNATURE_CHECK),)
+	@if [ ! -s $(BUILD_KEY) -o ! -s $(BUILD_KEY).pub ]; then \
+		echo Generate local signing keys... >&2; \
+		$(STAGING_DIR_HOST)/bin/usign -G \
+			-s $(BUILD_KEY) -p $(BUILD_KEY).pub -c "Local build key"; \
+		$(SCRIPT_DIR)/opkg-key add $(BUILD_KEY).pub; \
+	fi
+	if [ ! -s $(BUILD_KEY).ucert ]; then \
+		echo Generate local certificate... >&2; \
+		$(STAGING_DIR_HOST)/bin/ucert -I \
+			-c $(BUILD_KEY).ucert \
+			-p $(BUILD_KEY).pub \
+			-s $(BUILD_KEY); \
+	fi
+endif
+
 image:
 	$(MAKE) -s _check_profile
+	$(MAKE) -s _check_keys
 	(unset PROFILE FILES PACKAGES MAKEFLAGS; \
 	$(MAKE) -s _call_image \
 		$(if $(PROFILE),USER_PROFILE="$(PROFILE_FILTER)") \
 		$(if $(FILES),USER_FILES="$(FILES)") \
 		$(if $(PACKAGES),USER_PACKAGES="$(PACKAGES)") \
 		$(if $(BIN_DIR),BIN_DIR="$(BIN_DIR)") \
+		$(if $(DISABLED_SERVICES),DISABLED_SERVICES="$(DISABLED_SERVICES)") \
 		$(if $(USE_CFG),USER_PACKAGES="$(PACKAGES) $(shell cat $(USE_CFG))") \
-		$(if $(DISABLED_SERVICES),DISABLED_SERVICES="$(DISABLED_SERVICES)"))
+		$(if $(ROOTFS_PARTSIZE),CONFIG_TARGET_ROOTFS_PARTSIZE="$(ROOTFS_PARTSIZE)"))
 
 manifest: FORCE
 	$(MAKE) -s _check_profile
+	$(MAKE) -s _check_keys
 	(unset PROFILE FILES PACKAGES MAKEFLAGS; \
 	$(MAKE) -s _call_manifest \
 		$(if $(PROFILE),USER_PROFILE="$(PROFILE_FILTER)") \
 		$(if $(PACKAGES),USER_PACKAGES="$(PACKAGES)"))
 
-.SILENT: help info image manifest
+package_whatdepends: FORCE
+ifeq ($(PACKAGE),)
+	@echo 'Variable `PACKAGE` is not set but required by `whatdepends`'
+	@exit 1
+endif
+	@$(MAKE) -s package_reload
+	@$(OPKG) whatdepends -A $(PACKAGE)
+
+package_depends: FORCE
+ifeq ($(PACKAGE),)
+	@echo 'Variable `PACKAGE` is not set but required by `package_depends`'
+	@exit 1
+endif
+	@$(MAKE) -s package_reload
+	@$(OPKG) depends -A $(PACKAGE)
+
+
+.SILENT: help info image manifest package_whatdepends package_depends
